function tvm_functionToMFile(configuration)
%% Parse configuration
subjectDirectory        = tvm_getOption(configuration, 'i_RootDirectory', pwd());
    % default: current working directory
    %no default
functionName            = tvm_getOption(configuration, 'i_Function');
    %no default
append                  = tvm_getOption(configuration, 'i_Append');
    %no default
mFile                   = fullfile(subjectDirectory, tvm_getOption(configuration, 'o_Mfile'));
    %no default

%% 
configuration = rmfield(configuration, 'i_Function');
configuration = rmfield(configuration, 'i_Append');
configuration = rmfield(configuration, 'o_Mfile');

if append
    f = fopen(mFile, 'a');
else
    f = fopen(mFile, 'w');
    fprintf(f, '%% This file is automatically generated\n\n');
end

fprintf(f, '%%%%\n');
fprintf(f, 'cfg = [];\n');
fieldNames = fieldnames(configuration);
for i = 1:length(fieldNames)
    if ischar(configuration.(fieldNames{i}))
        fprintf(f, 'cfg.%s = ''%s'';\n', fieldNames{i}, configuration.(fieldNames{i}));
    elseif iscell(configuration.(fieldNames{i}))
        fprintf(f, 'cfg.%s = {', fieldNames{i});
        fprintf(f, '''%s'' ', configuration.(fieldNames{i}){:});
        fprintf(f, '};\n');
    elseif isnumeric(configuration.(fieldNames{i}))
        fprintf(f, 'cfg.%s = %f;\n', fieldNames{i}, configuration.(fieldNames{i}));
    end
end

fprintf(f, '%s(cfg);\n\n', functionName);
fclose(f);

end %end function
