function labels = tvm_exportFreesurferLabel(fileName, labels)

f = fopen(fileName, 'w');
fprintf(f, '#generated by tvm_exportFreesurferLabel\n');

fprintf(f, '%d\n', size(labels, 1));

labels = [labels, zeros(size(labels, 1), 3), zeros(size(labels, 1), 1)];
fprintf(f, '%d\t%3.3f\t%3.3f\t%3.3f\t%1.10f\n', labels');
fclose(f);


end %end function








