function tvm_workInProgress

errorMessage = [...
'              //\\\\           \n' ...
 '             //  \\\\          \n' ...
 '            //    \\\\         \n' ...
 '           //   O  \\\\        \n' ...
 '          //  _--_ \\\\       \n' ...
 '         // / ///    \\\\      \n' ...
 '        // / /// \\    \\\\     \n' ...
 '       //   /  |  \\@@  \\\\    \n' ...
 '      //   /   |  @@@@  \\\\   \n' ...
 '     //                  \\\\  \n' ...
 '    //||||||||||||||||||||\\\\ \n'];

warning('Work in progress');
fprintf(errorMessage);

end %end function


